name: Veracode Static Analysis Pipeline Scan

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-pipeline-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java (Temurin 8)
      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean package -B --file pom.xml

      # Step 4: Zip compiled output for Veracode scanning
      - name: Zip target directory
        run: zip -r veracode-scan-target.zip ./target

      # Step 5: Download Veracode Pipeline Scan tool
      - name: Download Veracode Pipeline Scan tool
        run: |
          curl --silent --show-error --fail -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -o pipeline-scan-LATEST.zip

      # Step 6: Run Veracode Pipeline Scan
      - name: Run Veracode Scan
        run: |
          java -jar pipeline-scan.jar \
          --veracode_api_id "${{ secrets.VERACODE_API_ID }}" \
          --veracode_api_key "${{ secrets.VERACODE_API_KEY }}" \
          --fail_on_severity="Very High, High" \
          --file veracode-scan-target.zip
        continue-on-error: true

      # Step 7: Convert results.json to SARIF only if scan succeeded
      - name: Convert scan results to SARIF
        if: success()
        id: convert
        uses: veracode/veracode-pipeline-scan-results-to-sarif@ff08ae5b45d5384cb4679932f184c013d34da9be
        with:
          pipeline-results-json: results.json

      # Step 8: Upload SARIF results to GitHub code scanning (if file exists)
      - name: Upload SARIF to GitHub
        if: success()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: veracode-results.sarif
