name: Veracode Static Analysis Pipeline Scan

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-pipeline-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java 8 (Temurin distribution)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'

      # Build the project using Maven (no subdirectory needed if pom.xml is in the root)
      - name: Build with Maven
        run: mvn clean package -B --file pom.xml

      # Zip the compiled output (recommended to scan only what's needed)
      - name: Prepare scan artifact
        run: zip -r veracode-scan-target.zip ./target

      # Download the Veracode Static Analysis Pipeline scan jar
      - name: Download Veracode Pipeline Scan
        run: |
          curl --silent --show-error --fail -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -o pipeline-scan-LATEST.zip

      # Run Veracode Pipeline scan
      - name: Run Veracode Scan
        run: |
          java -jar pipeline-scan.jar \
          --veracode_api_id "${{secrets.VERACODE_API_ID}}" \
          --veracode_api_key "${{secrets.VERACODE_API_KEY}}" \
          --fail_on_severity="Very High, High" \
          --file veracode-scan-target.zip
        continue-on-error: true

      # Convert pipeline scan output to SARIF format
      - name: Convert scan results to SARIF
        id: convert
        uses: veracode/veracode-pipeline-scan-results-to-sarif@ff08ae5b45d5384cb4679932f184c013d34da9be
        with:
          pipeline-results-json: results.json

      # Upload SARIF results to GitHub
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: veracode-results.sarif

